# Generated by Django 4.0.5 on 2022-07-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0003_member_jumin_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('cname', models.TextField(primary_key=True, serialize=False)),
                ('img', models.TextField(default='')),
                ('innertrait', models.TextField()),
                ('fighttrait', models.TextField()),
                ('skill', models.TextField()),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'shop',
                'ordering': ['cname'],
            },
        ),
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pay.shop')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
            ],
            options={
                'db_table': 'possession',
                'ordering': ['id'],
            },
        ),
    ]
