# Generated by Django 4.0.5 on 2022-06-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
