# Generated by Django 4.0.5 on 2022-07-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='jumin',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
